tabs:
        position: left
        show: switching
content:
        pdfjs: true
downloads:
        location:
                directory: '~/usr/Downloads'
        remove_finished: 0
completion:
        show: auto
colors:
        webpage:
                prefers_color_scheme_dark: true
fonts:
        default_family: 'VictorMono Nerd Font Mono'
        default_size: 10pt
